language: node_js
node_js: 
  - node

script:
  - npm run coverage

before_install:
  - npm i

env:
  global:
    - NODE_ENV=test
    - DB_DATABASE=authorshaven
    - DB_USERNAME=authorshaven
    - DB_PASSWORD=secret

cache: 
  directories: 
    - "node_modules"

after_success:
  - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info  

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE authorshaven;' -U postgres
  - psql -c "CREATE USER authorshaven WITH PASSWORD 'secret';" -U postgres
  - npm run migrate

notifications:
  email: false
