language: node_js

deploy:
  provider: heroku
  api_key:
    secure: ""

node_js: 
  - node

script:
  - npm run coverage
before_install:
  - npm i 
cache: 
  directories: 
    - "node_modules"

after_success:
    - ./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info  
