language: node_js

node_js: 
  - node

cache: npm

env:
  global:
    - NODE_ENV=test

after_success:
  - npm run coverage

before_install:
  - npm i 

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE authorshaven;' -U postgres
  - psql -c "CREATE USER authorshaven WITH PASSWORD 'secret';" -U postgres

notifications:
  email: false
