language: node_js

node_js: 
  - node

cache: npm

env:
  global:
    - NODE_ENV=test

after_success:
  - npm run coverage

before_install:
  - npm i 

services:
  - postgresql

before_script:
  - psql -c 'CREATE DATABASE authorshaven;' -U postgres
  - psql -c "CREATE USER authorshaven WITH PASSWORD 'secret';" -U postgres

notifications:
  email: false

deploy:
  provider: heroku
  api_key:
    secure: LSBCTDe94MVR8V7usyQBstsbd165GN6Gmh6/CAc5I61oVT1RPBY2hKeacT0rwfCS9y4pIpXrUBQyMZbA7nEUtOulsQJ4i8T0Oin5dqSchJAhWJOdOtgNE2EQrbKVc4Xoz2AfA0uci7/icAf4mEfqFi0MPB8qBEkvxsq9FyceMuINdsYRF+hWbsgyr42xUtuTPLBQnQP+DD+hhkyQQXUZTxOXa7VUQ0A8X8EEZ6oZigKLApMf1cwafzf64vaTxX5IXv03OWDPe0f1ekNdULFPCEcQSc2aeSRsNnVXMtM8v0e+ZZ3NzHswgp8+g15l75v5FtbUXTVo4510Br6DKkRjoLRCqf/1XltlWwfBwkHGMOzE3+9XPvtsu5NhbY9qEese+E/x+khz6mZh5U223YVpHfhaeq3NfoTs9wLfMaq+FCZv3tKFWVDeBH6fHbDS5h/mdequS8GddsuoA8kWQPzOzEo1KOf7QZ6C5cXAFjJRDkUWvduUeCFaUgcxDiRvTR0aJecyi8hrZ24UHdwP49Y+tjCImiBpSDYozEDTEtEQlS/TyYfPGGgj1ntGg1cfsIvhRkDje46WIa3kqkbsm8xfJF8Bk6T8F583GcONOLxh/Q7po6nROsnUvt9BJDDLVLbA+zDqCJa+nthBjS6IpFV87gmbbwjOItoGun5bMvID15s=
  app:
    staging: apollo-ah-backend-staging
    master: apollo-ah-backend
  run:
    - "npm run migrate"
    - "npm run seed"
